# Gradle
org.gradle.jvmargs=-Xms512m -Xmx4g -XX:MaxMetaspaceSize=768m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=1 -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.workers.max=3
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn
org.gradle.configureondemand=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official
kotlin.suppressGradlePluginWarnings=NonKmpAgpIsDeprecated
kotlin.incremental.native=true
kotlin.native.binary.smallBinary=true
kotlin.native.ignoreDisabledTargets=true
kotlin.daemon.jvmargs=-Xms512m -Xmx2500m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=1 -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false

# App versioning
versionMajor=1
versionMinor=6
versionPatch=3
versionPrerelease=
versionPrereleaseVersion=10

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
